### ISSUE TITLE
Extract HTML helpers (edit mode panel, etc.) to a separate library

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-sample-app-net#110]
### Motivation

Some HTML helpers can be reused in production projects.

### Proposed solution

Extract HTML helpers to a separate project: https://github.com/Kentico/kontent-aspnetcore

Outstanding:
- [x] Convert HTML helpers to tag helpers (both in the [sample app](https://github.com/Kentico/kontent-sample-app-net) and in the [boilerplate](https://github.com/Kentico/kontent-boilerplate-net)
- [x] Make the tag helpers easily configurable (remove dependencies on [`IConfiguration`](https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat/Helpers/Extensions/HtmlHelperExtensions.cs#L57))
- [x] Extract Image/Asset HTML helpers from the [sample app](https://github.com/Kentico/kontent-sample-app-net)
- [x] Consolidate with Image/Asset HTML helpers from the [boilerplate](https://github.com/Kentico/kontent-boilerplate-net)
- [ ] Extract Edit Panel HTML helpers from the [sample app](https://github.com/Kentico/kontent-sample-app-net)
- [x] Publish as a NuGet package

To be considered:
- extracting [ImageUrlBuilder](https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery/Builders/ImageTransformation/ImageUrlBuilder.cs) from the Delivery SDK
- extracting [EditLinkUrlBuilder](https://github.com/Kentico/kontent-management-sdk-net/tree/master/Kentico.Kontent.Management.Helpers) from the Management SDK

**Comment by petrsvihlik** [comment]
Outstanding:
- [ ] Extract Image/Asset HTML helpers from https://github.com/Kentico/kontent-sample-app-net
- [ ] Consolidate with Image/Asset HTML helpers from https://github.com/Kentico/kontent-boilerplate-net
- [ ] Extract Edit Panel HTML helpers from https://github.com/Kentico/kontent-sample-app-net
- [ ] Convert HTML helpers to tag helpers

**Comment by petrsvihlik** [comment]
## Configuration
@ewomack2000 the "edit mode" code was rewritten to use tag helpers 
- [EditLinkTagHelper](https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat/TagHelpers/EditLinkTagHelper.cs)
- [EditPanelTagHelper](https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat/TagHelpers/EditPanelTagHelper.cs)

which depend on the `IEditLinkBuilder` which can be injected via DI. The configuration of the mentioned service is shown in the [`Startup`](https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat/Startup.cs#L37-L39) class and the final usage in the [FactAboutUsViewModel.cshtml](https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat/Views/Shared/DisplayTemplates/FactAboutUsViewModel.cshtml).

So the configuration should now be in line with netcore's best practices.

## Extracting the code
@xantari given the number of custom CSS classes in the [EditPanelTagHelper](https://github.com/Kentico/kontent-sample-app-net/blob/eda075990f26ceca7012afbcd70384950d2d71b7/DancingGoat/TagHelpers/EditPanelTagHelper.cs#L38-L51), I don't think this is a good candidate to be extracted to https://github.com/Kentico/kontent-aspnetcore. If everything was made parametrizable, it would make things unreadable and bring almost no added value. What do you think? Do you see a better way to do it?

**Comment by petrsvihlik** [comment]
Oh yeah, and I almost forgot - I cleaned up the readme. It should contain less fluff and more up-to-date info.

https://github.com/Kentico/kontent-sample-app-net/blob/master/README.md

**Comment by xantari** [comment]
Yeah those EditPanel ones are hard. I agree they probably should be left only in the dancing goat sample and not in the main nuget packages.

**Comment by petrsvihlik** [comment]
thanks for the confirmation @xantari ! 
I'm closing this issue now...let's see if we identify more stuff that could be extracted to https://github.com/Kentico/kontent-aspnetcore
