### ISSUE TITLE
Localized URLs don't return expected localized pages

### ISSUE THREAD

**Issue by kentico-michaelb** [Kentico/kontent-sample-app-net#112]
### Brief bug description

Entering a URL containing the Spanish culture code or localized route without culture code directly into the address bar returns the default English version of the page or returns 404. 

Using the navigation bar also yields unexpected address bar URLs.

**Actual vs. Expected Results:**
1. Directly entered URLs and results:
- **https://localhost/es-ES/Inicio** == results in a 404
  - Expected result: Spanish home page returned
- **https://localhost/Inicio** == results in the English version of the Home page
  - Expected result: Spanish home page returned
- **https://localhost/es-ES/Artículos** == results in a 404
  - Expected result: Spanish article listing page returned
- **https://localhost/Artículos** == results in the English version of the Home page
  - Expected result: Spanish article listing page returned

2. The English home page catches some invalid urls:
- **https://localhost/adasdadasdasd/Home** == results in the English version of the Home page
  - Expected result: 404 page returned.

3. Using the links in the navigation bar render the English controller name even when the Spanish language has been chosen:

**Steps for Repro:**

1. Click "Spanish" from the language selector on Home
2. Click "Artículos" in the navigation bar

- Actual result: Spanish article listing page is rendered, but the URL in the address bar reads "https://localhost/es-ES/Articles"
  - Expected result: URL in the address bar reads "https://localhost/es-ES/Artículos"

**Comment by petrsvihlik** [comment]
@tomasjurasek could you please take a look at the issues? Mike is working on an article with the best practices for navigation so we need to resolve the issues here first.

**Comment by tomasjurasek** [comment]
Hi,

I found some problems with an ActionLink component - this component actually not work correctly with multilingual routing. I replaced this component with classic action link `<a asp-controller="" ... />` in the PR.

**Comment by tomasjurasek** [comment]
@kentico-michaelb, I don't know if these two scenarios are correct.  The is set up culture provider in the path. If there is no culture, the application don't know which culture used by URL.

* https://localhost/Inicio == results in the English version of the Home page
 Expected result: Spanish home page returned

* https://localhost/Artículos == results in the English version of the Home page
Expected result: Spanish article listing page returned


The other scenarios will be fixed in the PR.

**Comment by petrsvihlik** [comment]
@tomasjurasek yeah, these two should return 404
