### ISSUE TITLE
Edit Model Panel target=_blank links should have rel="noopener" added

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-sample-app-net#114]
This is something that came up during SEO review of our implementation of Kentico, and we had copied this stuff from the dancing goat sample.

The Edit toolbar's / links should have rel="noopener" added whenever there is a target=_blank. It allows the new target window to not have access to the prior windows "window" object in javascript. It's a security best practice item during the Lighthouse testing in chrome.

https://github.com/Kentico/kontent-sample-app-net/blob/80a84b80f2099b5cb75044671fe915f75793766a/DancingGoat/TagHelpers/EditPanelTagHelper.cs#L50

Reference: https://web.dev/external-anchors-use-rel-noopener/

**Comment by petrsvihlik** [comment]
well spotted :) fixed
