### ISSUE TITLE
Self config still shows Kentico Cloud logo

### ISSUE THREAD

**Issue by ondrabus** [Kentico/kontent-sample-app-net#115]
Check out the file https://github.com/Kentico/kontent-sample-app-net/blob/master/DancingGoat/Areas/Admin/Views/Shared/_Layout.cshtml - it contains SVG with Kentico Cloud logo. The overall feel of the page is Kentico-Cloud-like.

![image](https://user-images.githubusercontent.com/18418488/91270006-481a5b00-e778-11ea-9a76-a54a9710cd7c.png)

The page should be updated to have Kentico Kontent look and feel.

**Comment by petrsvihlik** [comment]
it could use complete redesign but we should wait with that until the product's redesigned. so I only replaced the logo.
