### ISSUE TITLE
Building sample app on Mac OS

### ISSUE THREAD

**Issue by hzik** [Kentico/kontent-sample-app-net#116]
This project configuration contains Windows Powershell paths that cause errors when building the app on Mac OS.

**Comment by petrsvihlik** [comment]
Suggested solution:

- add an OS condition to the csproj file ` Condition=" '$(OS)' == 'Windows_NT' "`
  - see https://stackoverflow.com/questions/43499222/how-to-get-the-current-operating-system-in-msbuild

If it's possible to make it run on Mac, let's add a similar condition+an `.sh` script to the project. If not, let's stick with the `Windows_NT` condition only.

**Comment by petrsvihlik** [comment]
Once the solution is ready, let's fix it in https://github.com/Kentico/kontent-boilerplate-net too.

**Comment by petrsvihlik** [comment]
I unintentionally solved it in a different project --> reassigning to myself.
