### ISSUE TITLE
CI Build fails for PRs outside of this repo

### ISSUE THREAD

**Issue by jankalfus** [Kentico/kontent-sample-app-net#127]
The CI build fails for PRs made from outside of this repo. It works for branches pushed into this repo directly only.

See https://github.com/Kentico/kontent-sample-app-net/pull/123#issuecomment-848664462

**Comment by Simply007** [comment]
The first thing would be to add `-Force` argument to the `Remove-Item` command in `publish.ps1` - https://github.com/Kentico/kontent-sample-app-net/blob/master/publish.ps1#L3

**Comment by Simply007** [comment]
Fixed and tested in #133

**Comment by Simply007** [comment]
Fixed and tested in #133
