### ISSUE TITLE
Add a test project

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/kontent-sample-app-net#76]
**Blocked** by #35 .

### Motivation

The sample application is often used to demo the overall concept of headless CMS to non-technical people. It is highly undesired to see exceptions or perhaps missing pieces of content in the output pages.

### Proposed solution

Once the application is ported to ASP.NET Core MVC, it will make sense to add a test project. 

- [x] Create an example unit test that would test controller by providing mocked responses as described  [here](https://github.com/Kentico/delivery-sdk-net/wiki/Faking-responses).
- [ ] Add an example of a UI test
- [x] Make sure the tests run locally and in AppVeyor

### Reference

* https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/test-asp-net-core-mvc-apps
* https://github.com/Kentico/delivery-sdk-net/wiki/Faking-responses
* https://dzone.com/articles/setup-selenium-web-browser-automation-using-aspnet-1
* https://github.com/seleniumhq/selenium
* https://www.appveyor.com/docs/how-to/selenium-testing/

**Comment by petrsvihlik** [comment]
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.1

**Comment by petrsvihlik** [comment]
we have a sample unit test project
