### ISSUE TITLE
Spike: Try deploy to zeit

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-sample-app-net#78]
### Motivation

It would be nice to have a live demo of the site. Ideally, we'd like to have the site deployed as a part of the build process.

### Proposed solution

Let's try whether Zeit is the right service for us. First, let's try a one-time deployment and then we can talk about integrating it in the CI/CD pipeline.

### Additional context

- https://zeit.co/
- https://www.hanselman.com/blog/ImprovementsOnASPNETCoreDeploymentsOnZeitsNowshAndMakingSmallContainerImages.aspx

**Comment by Yusadolat** [comment]
If I get you right, You need someone to deploy this to Zeit right?

**Comment by petrsvihlik** [comment]
1) Try the deployment to Zeit
2) Come up with configuration (dockerfile?) that we could use to continuously deploy the site

**Comment by Yusadolat** [comment]
Ohh, I get.

I'm on it :smile:

**Comment by petrsvihlik** [comment]
Cool @Yusadolat! I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

**Comment by petrsvihlik** [comment]
no response -> unassigning

**Comment by petrsvihlik** [comment]
zeit now 2.0 no longer supports docker :(((
