### ISSUE TITLE
Migrate the application to ASP.NET Core MVC

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-sample-app-net#90]
Target ASP.NET Core version: [3.1](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)

**Expected changes:**
- NuGet packages:
  - microsoft.* and system.* should be fine (they should have their .net standard alternative)
  - anglesharp supports netstandard = ok
  - kenticocloud.* supports netstandard = ok
  - jquery&bootstrap are not dependent on clr = ok
  - antlr is used by webgrease which is used by Microsoft.AspNet.Web.Optimization (for js/css bundling)...we can replace it with an analogical asp.net core package...see the docs
- [Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?tabs=basicconfiguration).
- take advantage of Dependency Injection to inject services like `DeliveryClient` into controllers.
- There may be some places where we can make use of the [view components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components) and some other new ASP.NET Core functionality. 
- Changes in [multilingual support](https://andrewlock.net/url-culture-provider-using-middleware-as-mvc-filter-in-asp-net-core-1-1-0/)
- [`appveyor.yml`](https://github.com/Kentico/cloud-sample-app-net/blob/master/appveyor.yml) in case the build procedure needs some adjustments (e.g. change the platform)

**Workflow:**
- We won't merge it to `master` until it's done and thoroughly tested. 
- Before we merge the changes, we'll backup the original code in a separate branch. 

Feel free to refactor the code to use the latest standards.

Other things to consider during the conversion:
- See [ASP.NET Announcements](https://github.com/aspnet/Announcements/issues) to have more context about the changes in the new releases

**Comment by JanLenoch** [comment]
Hey guys, want to collaborate w/ David Fowler and get some first-class guidance? See https://twitter.com/davidfowl/status/1128522247889539072

BTW, I'll discuss that with my team so that I can jump in (in case no one else can).

**Comment by Simply007** [comment]
I agree.

**Comment by amoraitis** [comment]
Working👨🏻‍💻 on this at #101. You could assign this to me, also backup the current master branch to a new one.

**Comment by petrsvihlik** [comment]
Thanks for working on this @amoraitis! We'll back up the master branch just before merging the PR.

**Comment by amoraitis** [comment]
@petrsvihlik @JanLenoch @Simply007 
Question: Is the [ControllerBase](https://github.com/Kentico/cloud-sample-app-net/blob/master/DancingGoat/Controllers/ControllerBase.cs)'s `CreateDeliveryClient()` a service we have to register in the Startup.cs file or what?

**I cannot find out the value of this method in the specific controller**

My propose:

1. Create a service which will implement the [`CreateDeliveryClient()`](https://github.com/Kentico/cloud-sample-app-net/blob/ae6cb700d1d8d08b6e8141403c6198a796c9c2bc/DancingGoat/Controllers/ControllerBase.cs#L32-#L46)
2. Create an interface for this one
3. Register it as a service in the Startup.ConfigureServices()(Decide what [type of service](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#lifetime-and-registration-options) is this?)
4. Use it with dependency injection in the HomeController and in the constructor create the DeliveryClient

**Comment by petrsvihlik** [comment]
I'd stick with the current implementation for now.
Btw - ` var projectId = _deliveryOptions.ProjectId ?? _settingProvider.ProjectId?.ToString();` the value is not used anywhere. Previously, it was used for initializing the `_deliveryOptions.ProjectId` if it was null...

**Comment by xantari** [comment]
Hi,

My suggestion is to have both .NET samples available (the current full framework example), as well as a new .NET Core sample.

**Comment by petrsvihlik** [comment]
hi @xantari the idea is to backup the current (full .NET framework) sample site in a separate branch/git tag and continue maintaining the only the .net core one. it makes sense since all the .net frameworks will become .NET 5 in the future: https://devblogs.microsoft.com/dotnet/introducing-net-5/

**Comment by petrsvihlik** [comment]
.NET Core 3.1 prototype can be found in https://github.com/Kentico/kontent-sample-app-net/tree/aspnet-core-2.2

**fixed:**
1. fixed layout
2. fixed childactions -> view components
3. switched to IConfiguration
4. fixed store, map, contact us JS
5. deliveryclient -> factory (for multilingual)
6. selfconfig action filter -> via DI
7. selfconfig get shared pid & get from app pid
8. fixed datetime formatting
9. fixed image assets
10. fixed path to views
11. fixed footer
12. migrated to netcore3.1
13. fixed localization (resx)

**outstanding:** 
1. multilingual
2. editpanel - not tested (maybe works??)
3. wizard - needs extra effort
4. clean up the js/css mess and bundling

**Comment by petrsvihlik** [comment]
1. multilingual - done
2. editpanel - fixed and tested
3. wizard - fixed and tested
----------------------------
outstanding:
- hot reload of DeliveryOptions
- clean up the js/css mess and bundling

**Comment by petrsvihlik** [comment]
done!
